# Generated by Django 4.0.3 on 2022-04-08 17:59

from uuid import uuid4
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('thumbnailurl', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(max_length=10)),
                ('comments', models.ManyToManyField(related_name='video_comments', to='videos.Comment', blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Channel')),
                ('likes', models.ManyToManyField(related_name='video_likes', to=settings.AUTH_USER_MODEL, blank=True)),
                ('dislikes', models.ManyToManyField(related_name='video_dislikes', to=settings.AUTH_USER_MODEL, blank=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('videos', models.ManyToManyField(blank=True, related_name='playlist_videos', to='Videos.video')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_channel', to='Videos.Channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Videos.video')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid4, unique=True, editable=False, blank=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('icon', models.URLField(blank=True)),
                ('banner', models.URLField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('playlists', models.ManyToManyField(blank=True, related_name='playlists', to='Videos.playlist')),
                ('subcriptions', models.ManyToManyField(blank=True, related_name='subscriptions', to='Videos.channel')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, related_name='videos', to='Videos.video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
